import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@/src/css/bootstrap.min.css'
import Navbar from "@/src/components/Navbar"
import Footer from "@/src/components/Footer"
import {Providers} from "@/src/Providers";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (<>
  
    <html lang="en"><body className={inter.className}><Providers><Navbar/><div>{children}</div>
    <Footer/></Providers></body>
    </html>
    
    </>
  )
}
